<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    {{-- A5, per §6.6. --}}
    <style>
        @page { size: A5; margin: 14mm 12mm; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 10pt; color: #111; }
        .wordmark { font-size: 17pt; font-weight: bold; letter-spacing: -0.4pt; }
        .head { border-bottom: 1.5pt solid #111; padding-bottom: 5mm; margin-bottom: 5mm; }
        .head td { vertical-align: bottom; }
        .muted { color: #666; font-size: 8.5pt; }
        table { width: 100%; border-collapse: collapse; }
        .kv td { padding: 1.1mm 0; }
        .kv .label { color: #555; width: 42%; }
        .kv .value { text-align: right; font-weight: 600; }
        .items { margin-top: 4mm; }
        .items th { text-align: left; border-bottom: 0.6pt solid #bbb; padding: 1.5mm 0; font-size: 8.5pt; color: #555; }
        .items td { padding: 1.3mm 0; border-bottom: 0.4pt solid #eee; }
        .right { text-align: right; }
        .total { margin-top: 4mm; border-top: 1.5pt solid #111; padding-top: 3mm; }
        .total td { font-size: 13pt; font-weight: bold; padding-top: 1mm; }
        .void { color: #c0202a; border: 1.5pt solid #c0202a; padding: 2mm 3mm; font-weight: bold;
                text-align: center; margin-top: 4mm; font-size: 11pt; }
        .foot { margin-top: 9mm; text-align: center; color: #777; font-size: 8pt;
                border-top: 0.4pt solid #ddd; padding-top: 3mm; }
    </style>
</head>
<body>

<table class="head">
    <tr>
        <td>
            <div class="wordmark">CafeTrack</div>
            <div class="muted">{{ $cafe->name }}</div>
        </td>
        <td class="right">
            <div style="font-weight:bold;">Invoice #{{ $invoice->id }}</div>
            <div class="muted">{{ $createdAt }}</div>
        </td>
    </tr>
</table>

<table class="kv">
    <tr><td class="label">Station</td><td class="value">{{ $stationName }}</td></tr>
    <tr><td class="label">Customer</td><td class="value">{{ $customerName }}</td></tr>
    <tr><td class="label">Phone / ID</td><td class="value">{{ $customerPhone }}</td></tr>
    <tr><td class="label">Session start</td><td class="value">{{ $startTime }}</td></tr>
    <tr><td class="label">Session end</td><td class="value">{{ $endTime }}</td></tr>
    <tr><td class="label">Billed time</td><td class="value">{{ $billedTime }}</td></tr>
    <tr><td class="label">Controllers</td><td class="value">{{ $controllers }}</td></tr>
    <tr><td class="label">Hourly rate</td><td class="value">৳{{ $hourlyRate }}</td></tr>
    <tr><td class="label">Play charge</td><td class="value">৳{{ $sessionAmount }}</td></tr>
    <tr><td class="label">Payment method</td><td class="value">{{ $paymentMethod }}</td></tr>
    <tr><td class="label">Payment status</td><td class="value">{{ ucfirst($invoice->payment_status) }}</td></tr>
</table>

@if ($invoice->items->isNotEmpty())
    <table class="items">
        <thead>
        <tr>
            <th>Item</th>
            <th class="right" style="width:12%;">Qty</th>
            <th class="right" style="width:24%;">Amount</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($invoice->items as $item)
            <tr>
                <td>{{ $item->description }}</td>
                <td class="right">{{ $item->quantity }}</td>
                <td class="right">৳{{ \App\Support\Money::str($item->amount) }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif

@if ($hasDiscount)
    <table class="kv" style="margin-top:3mm;">
        <tr>
            <td class="label">Discount{{ $invoice->discount_reason ? ' — '.$invoice->discount_reason : '' }}</td>
            <td class="value">−৳{{ $discountAmount }}</td>
        </tr>
    </table>
@endif

<table class="total">
    <tr>
        <td>Total due</td>
        <td class="right">৳{{ $totalAmount }}</td>
    </tr>
</table>

@if ($invoice->status === 'void')
    <div class="void">VOID — {{ $invoice->void_reason }}</div>
@endif

<div class="foot">Thanks for playing at {{ $cafe->name }}. Generated by CafeTrack.</div>

</body>
</html>
